ALTER TABLE session_template
    ADD COLUMN IF NOT EXISTS engine VARCHAR(255);

CREATE TABLE IF NOT EXISTS system_config (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    default_engine VARCHAR(255) NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS system_config_SEQ START WITH 1 INCREMENT BY 50;
