package db.migration;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Savepoint;
import java.sql.Statement;
import java.util.Locale;
import java.util.OptionalLong;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;
import org.jboss.logging.Logger;

/**
 * Creates the {@code agent_SEQ} sequence that {@code AgentEntity} (a {@code PanacheEntity}) needs, and
 * drops the orphaned {@code actor_SEQ} (issue #445).
 *
 * <p>V19 created {@code actor_SEQ}; V45 renamed the {@code actor} table to {@code agent} but never created
 * {@code agent_SEQ}, so Hibernate {@code validate} failed on a database built purely from migrations.</p>
 *
 * <p>This is a Java migration rather than SQL because the start value has to be computed from the data
 * ({@code max(agent.id)}), and neither H2 nor PostgreSQL accept a subquery in
 * {@code CREATE SEQUENCE ... START WITH}. Reading the value over JDBC and issuing DDL with a literal works
 * identically on both databases.</p>
 *
 * <p>The start value is {@code max(maxId + 50, currentSeq + 50)}. Hibernate uses the {@code pooled} optimizer
 * with an increment of 50, so a sequence value {@code V} hands out ids in {@code (V - 50, V]}; starting at
 * {@code max(id) + 50} guarantees that no generated id collides with an existing row, including rows inserted
 * earlier with ids drawn from {@code actor_SEQ}.</p>
 *
 * <p>An {@code agent_SEQ} may already exist, e.g. on an install whose schema was once generated by Hibernate.
 * It is never lowered: during a rolling upgrade another node still running the old version may have already
 * reserved a block of ids from that sequence without having persisted them yet, so {@code max(id)} alone can
 * be below ids that are in flight. Starting past the existing sequence value plus one block keeps those
 * reserved ids unique. If the existing value can't be read, the migration logs a warning and falls back to
 * {@code maxId + 50}.</p>
 */
public class V73__create_agent_sequence extends BaseJavaMigration {

    private static final Logger LOG = Logger.getLogger(V73__create_agent_sequence.class);

    /** Must match the Panache / Hibernate default allocationSize. */
    private static final long INCREMENT = 50L;

    /**
     * Applies the migration.
     *
     * @param context the Flyway migration context
     * @throws SQLException if a statement fails
     */
    @Override
    public void migrate(Context context) throws SQLException {
        Connection connection = context.getConnection();
        try (Statement statement = connection.createStatement()) {
            long maxId = 0L;
            try (ResultSet rs = statement.executeQuery("SELECT COALESCE(MAX(id), 0) FROM agent")) {
                if (rs.next()) {
                    maxId = rs.getLong(1);
                }
            }
            long start = maxId + INCREMENT;
            OptionalLong current = currentAgentSequenceValue(connection);
            if (current.isPresent()) {
                start = Math.max(start, current.getAsLong() + INCREMENT);
            }
            statement.execute("DROP SEQUENCE IF EXISTS agent_SEQ");
            statement.execute("CREATE SEQUENCE agent_SEQ START WITH " + start + " INCREMENT BY " + INCREMENT);
            statement.execute("DROP SEQUENCE IF EXISTS actor_SEQ");
        }
    }

    /**
     * Reads the current value of an existing {@code agent_SEQ}.
     *
     * <p>PostgreSQL: {@code last_value} of the sequence relation. H2 2.x: {@code BASE_VALUE} from
     * {@code INFORMATION_SCHEMA.SEQUENCES} (the next value to be returned). The read runs inside a savepoint
     * so that a failure doesn't abort the surrounding PostgreSQL transaction.</p>
     *
     * @param connection the migration connection
     * @return the current value, or empty if the sequence doesn't exist or its value can't be read
     * @throws SQLException if the existence check itself fails
     */
    private static OptionalLong currentAgentSequenceValue(Connection connection) throws SQLException {
        try (Statement statement = connection.createStatement();
                ResultSet rs = statement.executeQuery("SELECT COUNT(*) FROM INFORMATION_SCHEMA.SEQUENCES"
                        + " WHERE UPPER(SEQUENCE_NAME) = 'AGENT_SEQ'")) {
            if (!rs.next() || rs.getLong(1) == 0L) {
                return OptionalLong.empty();
            }
        }
        String product = connection.getMetaData().getDatabaseProductName().toLowerCase(Locale.ROOT);
        String sql = product.contains("postgres")
                ? "SELECT last_value FROM agent_SEQ"
                : "SELECT BASE_VALUE FROM INFORMATION_SCHEMA.SEQUENCES"
                        + " WHERE UPPER(SEQUENCE_NAME) = 'AGENT_SEQ'";
        Savepoint savepoint = connection.getAutoCommit() ? null : connection.setSavepoint();
        try (Statement statement = connection.createStatement(); ResultSet rs = statement.executeQuery(sql)) {
            if (rs.next()) {
                return OptionalLong.of(rs.getLong(1));
            }
            LOG.warnf("agent_SEQ exists but its value could not be read; starting at max(agent.id) + %d",
                    INCREMENT);
            return OptionalLong.empty();
        } catch (SQLException e) {
            if (savepoint != null) {
                connection.rollback(savepoint);
            }
            LOG.warnf(e, "Could not read current value of agent_SEQ; starting at max(agent.id) + %d",
                    INCREMENT);
            return OptionalLong.empty();
        } finally {
            if (savepoint != null) {
                try {
                    connection.releaseSavepoint(savepoint);
                } catch (SQLException ignored) {
                    // Already released by rollback on some drivers.
                }
            }
        }
    }
}
